### ISSUE TITLE
Alter Headers on Retry

### ISSUE THREAD

**Issue by sgrtho** [serviejs/popsicle-retry#15]
Hi, this is a question - though very specific to popsicle-retry and its implementation - that's why I'm asking it here.

I'd like to use *Popsicle* to power an API SDK. The API supports an HTTP header-based *replay* feature, which allows to safely repeat a `POST` or `PUT` request - even if the original request has already been processed.

The header needs to carry two bits of information: a certain `id` and a boolean `flag`. If the boolean flag is set, the API backend will **always** look for a previous response and add a timing penalty before responding. If it is not set, it will process the request as it would normally do.

To properly use this feature, a normal request needs to carry headers `id` and `flag:false`. If the request times out and and is retried, it needs to carry headers `id` and `flag:true`. Is there a *non-hacky* way to achieve this? If not: at what point of the command chain does *Popsicle* fork the headers so that I could alter the flag right after? Thanks in advance.

**Comment by blakeembrey** [comment]
Would be extremely easy to expose a "pre-retry" option so you can mutate the request for it's sent. What do you think? You could do whatever you want at that step as a result.

**Comment by sgrtho** [comment]
Would be perfect enough 👍. Thanks in advance.

**Comment by blakeembrey** [comment]
Lost track of this ticket, I'm sorry! Since 4.x, this would possible by wrapping your `fn` passed to `retry`. E.g. `retry((req, next) => transport(req, next))` would allow you to do whatever you want before `transport` is called. The tricky part is tracking whether it's the same `req` being retried. This could be done by tracking URL requests externally, but I just added https://github.com/serviejs/popsicle-retry/commit/3cd580a774c92e47fd16b933129a83714fd5472c which would enable this it a little more cleanly if you wanted to track `originalRequest` (e.g. via `WeakMap`, this would allow you to track whether it's been seen before for `flag`).
